@startuml Diagramme d'activité de gestion des avis d'un film
title Diagramme d'activité de gestion des avis d'un film

(*) -down-> "Gestion avis d'un film"

"Gestion avis d'un film" --> "Ajout d'un avis"
"Gestion avis d'un film" --> "Modification d'un avis"
"Gestion avis d'un film" --> "Suppression d'un avis"


"Ajout d'un avis" --> if "Avis existant ?" then
  -left->[Oui, statut 403] "Gestion avis d'un film"
else
  -down->[Non] "Avis ajouté"
endif

"Modification d'un avis" --> if "Avis existant ?" then
  -down->[Oui] "Avis modifié"
else
  -->[Non, statut 404] "Gestion avis d'un film"
endif

"Suppression d'un avis" --> if "Avis existant ?" then
  -down->[Oui] "Avis supprimé"
else
  -->[Non, statut 404] "Gestion avis d'un film"
endif

"Avis ajouté" -->(*)
"Avis modifié" -->(*)
"Avis supprimé" -->(*)
@enduml
