@startuml Diagramme d'activité de gestion d'abonnement à un utilisateur
title Diagramme d'activité de gestion d'abonnement à un utilisateur

(*) -down-> "Utilisateur connecté sur l'application"

"Utilisateur connecté sur l'application" --> "Gestion de son abonnement à un utilisateur"
"Gestion de son abonnement à un utilisateur" --> "Ajout d'un utilisateur à sa liste d'éclaireurs"
"Gestion de son abonnement à un utilisateur" --> "Suppression d'un utilisateur de sa liste d'éclaireurs"


"Ajout d'un utilisateur à sa liste d'éclaireurs" --> if "Déjà éclaireur ?" then
  -->[Oui, statut 403] (*)
else
  -->[Non]"Ajout de l'éclaireur"
endif

"Ajout de l'éclaireur" -->(*)

"Suppression d'un utilisateur de sa liste d'éclaireurs" --> if "Déjà éclaireur ?" then
  -->[Oui] "Suppression de l'éclaireur"
else
  -->[Non, statut 404](*)
endif

"Suppression de l'éclaireur" -->(*)

@enduml
