@startuml Diagramme d'activité de consultation d'un film
title Diagramme d'activité de consultation d'un film

(*) -down-> "Utilisateur sur l'application"

"Utilisateur sur l'application" -right-> if "Utilisateur connecté ?" then
  -->[Oui] "Consultation de sa liste de films"
else
  -->[Non, statut 401] "Utilisateur sur l'application"
endif

"Utilisateur sur l'application" -down-> "Recherche de films"

"Recherche de films" --> if "Saisie valide ?" then
  -->[Oui] "Consultation d'une liste de films"
else
  -->[Non, statut 400] "Recherche de films"
endif

"Consultation de sa liste de films" --> "Tentative de sélection d'un film"
"Consultation d'une liste de films" --> "Tentative de sélection d'un film"

"Tentative de sélection d'un film" --> if "Id valide ?" then
  -->[Oui] "Film sélectionné"
else
  -->[Non, statut 404] "Tentative de sélection d'un film"
endif

"Film sélectionné" --> "Consultation de la fiche technique d'un film"
"Consultation de la fiche technique d'un film" -->(*)

"Film sélectionné" --> "Consultation des avis d'un film"
"Consultation des avis d'un film" -->(*)

"Film sélectionné" --> if "Utilisateur connecté ?" then
  -->[Oui] "Gestion de son avis sur le film"
else
  -->[Non, statut 401] "Film sélectionné"
endif

"Film sélectionné" --> if "Utilisateur connecté ?" then
  -->[Oui] "Consultation de l'avis de ses éclaireurs sur le film"
else
  -->[Non, statut 401] "Film sélectionné"
endif

"Gestion de son avis sur le film" -->(*)
"Consultation de l'avis de ses éclaireurs sur le film" -->(*)

@enduml
