@startuml Diagramme d'activité de recherche d'un utilisateur
title Diagramme d'activité de recherche d'un utilisateur

(*) -down-> "Utilisateur connecté sur l'application"

"Utilisateur connecté sur l'application" --> "Recherche d'utilisateurs"
"Utilisateur connecté sur l'application" --> "Consultation de sa liste d'éclaireurs"


"Recherche d'utilisateurs" --> if "Saisie valide ?" then
  -down->[Oui] "Consultation d'une liste d'utilisateurs"
else
  -->[Non, statut 400] "Recherche d'utilisateurs"
endif

"Consultation d'une liste d'utilisateurs" --> "Tentative de sélection d'un utilisateur"
"Consultation de sa liste d'éclaireurs" --> "Tentative de sélection d'un utilisateur"

"Tentative de sélection d'un utilisateur" --> if "Id valide ?" then
  -down->[Oui] "Utilisateur sélectionné"
else
  -->[Non, statut 404] "Tentative de sélection d'un utilisateur"
endif


"Utilisateur sélectionné" --> "Consultation des films en commun et des avis associés"
"Utilisateur sélectionné" --> "Gérer son abonnement à un utilisateur"
"Utilisateur sélectionné" --> "Consultation des films notés par l'utilisateur"

"Consultation des films en commun et des avis associés" -->(*)
"Gérer son abonnement à un utilisateur" -->(*)
"Consultation des films notés par l'utilisateur" -->(*)
@enduml
